### ISSUE TITLE
Allow specifying minimum VLAN group size when using `vlan.vlanlist_to_config`.

### ISSUE THREAD

**Issue by progala** [networktocode/netutils#101]
### Environment
* netutils version:  v1.0.0

### Proposed Functionality

Allow specifying minimum VLAN group size when using `vlan.vlanlist_to_config`.

Currently `vlanlist_to_config` will not group together two adjecent VLANs. Only groups of 3 or more VLANs are considered for `vlan_a-vlan_x` format conversion.

Proposal is to add `min_group_size` argument  that would allow caller to control the grouping behavior.

### Use Case

As an end user I want to be able to affect the way VLANs in the VLAN list are grouped. Some vendors, in their configuration, group two adjecent VLANs using `-` between the VLAN ids.

For example VLANs `4,5` would be represented as `4-5`.

Example output from the Arista EOS illustrating this use case:

```
nyc-leaf-01#sh run | in vlan
vlan 4-5,9-10,15,20,30
```

**Comment by itdependsnetworks** [comment]
Makes sense!

**Comment by jeffkala** [comment]
should this be configurable? Wondering if different s/w versions do this based on a different min adjacent vlans?

**Comment by jeffkala** [comment]
fixed in #105
