### ISSUE TITLE
WLC Parser

### ISSUE THREAD

**Issue by jdrew82** [networktocode/netutils#11]
### Environment
* netutils version:  1.0.0

### Proposed Functionality
Add a parser for Cisco WLC devices.

### Use Case
As a network tech it'd be very helpful to be able to parse WLC devices for compliance purposes.

**Comment by jdrew82** [comment]
@itdependsnetworks I've looked into this a bit and I think this is an error in the parser_map. It looks like it's currently using "cisco_aireos" mapping to the AIREOSParser class but if we're using the netmiko platforms then it should actually be cisco_wlc. I think the same could go for the bigip_f5 mapping.

**Comment by itdependsnetworks** [comment]
Just seeing this now. We may have done this based on PYNTC. I am not sure what the pros/cons are, but let me rope in @jmcgill298

**Comment by dgarros** [comment]
Is there a way to redefine this mapping per project if needed ? 
We won't be able to always have the name of the platform  matches the netmiko syntax.

**Comment by jmcgill298** [comment]
It was based off Ansible.

@dgarros it is today, the `network_os` arg must be passed to the filter. In this example as it is today:

```
my_parser_map:
  cisco_wlc: "cisco_aireos"
```

`data | filter(network_os={{ my_parser_map[my_name_for_os] }}, *args)`

**Comment by itdependsnetworks** [comment]
As Jacob mentioned, one can map the parser, this was also reflected in https://github.com/nautobot/nautobot-plugin-nornir/pull/20
