### ISSUE TITLE
[Feature]config.compliance: cisco & arista no shutdown

### ISSUE THREAD

**Issue by ryanmerolle** [networktocode/netutils#111]
### Environment
* netutils version:  1.1.0

### Proposed Functionality

Many people explicitly template out `no shutdown` under an interface.  In fact arista.avd's jinja templates do this by default.

It would be nice in the various config.compliance functions, to pass an argument to only trigger a diff for interfaces with `no shut` and `no shutdown` only if the config being compared to lists `shut` or `shutdown` under the same interface

### Use Case

Prevents unnecessary diff output.

### Example

running config
```
interface Ethernet1
  description test
  shutdown
!
interface Ethernet2
  description test2
 !
interface Ethernet3
  description test3
!
```

compliance config
```
interface Ethernet1
  description test
  no shutdown
!
interface Ethernet2
  description test2
  no shutdown
 !
interface Ethernet3
  description test3
  shutdown
!
```

current resulting diffed config
```
interface Ethernet1
  no shutdown
interface Ethernet2
  no shutdown
 interface Ethernet3
  shutdown
```

proposed resulting diffed config
```
interface Ethernet1
  no shutdown
 interface Ethernet3
  shutdown
```

**Comment by itdependsnetworks** [comment]
There are hundreds of these scenarios, and it is not something this project can consider. We are more explicit about the definition of compliance on nautobot’s golden config plugin, and we should add clarity here but not something we can consider to be in scope of this project. I will add details to clarify this.

**Comment by ryanmerolle** [comment]
Fair enough. Thanks!
