### ISSUE TITLE
[Feature]config.compliance: diff ip

### ISSUE THREAD

**Issue by ryanmerolle** [networktocode/netutils#112]
### Environment
* netutils version:  1.1.0

### Proposed Functionality

It would be nice in the various config.compliance functions, to pass an argument to trigger an output for ip changes "no-ing out" the orginal IP address for an interface when config differs with IPs.

### Use Case

Shows the old value

### Example

running config
```
interface Ethernet1
  description test1
  ip address 10.1.0.1/24
!
interface Ethernet2
  description test2
  ip address 10.2.0.1/24
 !
interface Ethernet3
  description test3
  ip address 10.3.0.1/24
!
interface Ethernet4
  description test4
!
```

compliance config
```
interface Ethernet1
  description test1
  ip address 10.1.0.1/24
!
interface Ethernet2
  description test2
  ip address 11.2.0.1/24
 !
interface Ethernet3
  description test3
!
interface Ethernet4
  description test4
  ip address 10.4.0.1/24
!
```

current resulting diffed config
```
interface Ethernet2
  ip address 11.2.0.1/24
interface Ethernet3
  no ip address
interface Ethernet4
  ip address 10.4.0.1/24
!
```

proposed resulting diffed config
```
interface Ethernet2
  no ip address 10.2.0.1/24
  ip address 11.2.0.1/24
interface Ethernet3
  no ip address 10.3.0.1/24
interface Ethernet4
  ip address 10.4.0.1/24
!
```

**Comment by itdependsnetworks** [comment]
Let me think about this one, it is unlikely, but will think about it. I think this is better handled in https://github.com/netdevops/hier_config tbh.

**Comment by ryanmerolle** [comment]
That also crossed my mind.  I figured I’d post the idea.

**Comment by qduk** [comment]
Closing as we decided this use case doesn't apply to our project.

**Comment by ryanmerolle** [comment]
Sounds good to me.  Thanks for considering.  I totally understand your view.
