### ISSUE TITLE
OUI Mapping

### ISSUE THREAD

**Issue by qduk** [networktocode/netutils#119]
### Environment
* netutils version:  1.1

### Proposed Functionality

The ability to translate MAC address OUI to vendor and vice-versa.

### Use Case
In the event that you have a mac address, you may want to know the manufacturer. For example, when querying devices connected to a switch.

**Comment by itdependsnetworks** [comment]
Can pull this incrementally. https://gitlab.com/wireshark/wireshark/-/raw/master/manuf

**Comment by qduk** [comment]
Closing as #148 was merged.
