### ISSUE TITLE
Mapping of IP protocol numbers to names and back

### ISSUE THREAD

**Issue by Kircheneer** [networktocode/netutils#120]
### Environment
* netutils version:  v1.1.0

### Proposed Functionality

Provide a dictionary like this: https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml

### Use Case

For example: Mapping protocol names into protocol numbers for performing firewalling.

**Comment by itdependsnetworks** [comment]
Should follow this PR pattern (and specific comment) https://github.com/networktocode/netutils/pull/35#issuecomment-895528535. Would be great to get this in.

**Comment by Kircheneer** [comment]
Turns out this is already in and I just didn't see it. Its not a documentation problem because it is right there in the documentation.
