### ISSUE TITLE
Document the out of the box jinja2_convenience_function syntax

### ISSUE THREAD

**Issue by ryanmerolle** [networktocode/netutils#150]
### Environment
* netutils version:  1.2.0

### Proposed Functionality

Document the jinja2_convenience_function filter functions similar to the way each function is documented.

### Use Case

This would allow users to better understand how to leverage jinja2_convenience_function filters in their jinja.

**Comment by itdependsnetworks** [comment]
fixed in #152

**Comment by ryanmerolle** [comment]
Awesome!
