### ISSUE TITLE
abbreviated_interface_name support for Vlan interfaces

### ISSUE THREAD

**Issue by ryanmerolle** [networktocode/netutils#158]
### Environment
* netutils version:  1.2.0

### Proposed Functionality

Vlan interfaces are often commonly shortened.  It would be nice for the interface tool to do the same.

### Use Case

``` python
>>>print(abbreviated_interface_name("Vlan99"))
Vl99
```

**Comment by ryanmerolle** [comment]
Interesting.  I was about to add this, but I see the constants are defined as https://github.com/networktocode/netutils/blob/develop/netutils/constants.py#L137-L141

```python
    "VLAN": "VLAN",
    "V": "VLAN",
    "Vl": "VLAN",
    "Vlan-interface": "VLAN",
    "vlan": "VLAN",
```

and https://github.com/networktocode/netutils/blob/develop/netutils/constants.py#L197

```python
    "VLAN": "Vl",
```

I would expect for _**interfaces**_ the mapping would be `"Vl": "Vlan"` and "Vlan": "Vl".  `VLAN` is mostly used for the VLAN definition and not the interface, but again I have been absorbed in Arista lately.

**Comment by ryanmerolle** [comment]
Oddly enough when I do the following, I would expect an output of `Vl99`, but I see `VL99`:

```python
>>> vlan_interface = "Vlan99"
>>>print(abbreviated_interface_name(vlan_interface.upper()))
VL99
```

**Comment by itdependsnetworks** [comment]
This works as well. 
```
>>> print(abbreviated_interface_name(canonical_interface_name("VLAN99")))
Vl99
>>>
```

Unfortunately, we need to anchor on something being correct. That being said, we have allowed you to override that definition of correct for this exact issue, see the signature

```
def abbreviated_interface_name(
    interface: str,
    addl_name_map: t.Optional[t.Dict[str, str]] = None,
    addl_reverse_map: t.Optional[t.Dict[str, str]] = None,
    verify: bool = False,
) -> str:
```

**Comment by ryanmerolle** [comment]
This totally makes sense.  You have to use something as a basis to anchor.

To correct your example, I would need to adjust to this:

```python
>>> vlan_interface = "Vlan99"
>>> print(abbreviated_interface_name(canonical_interface_name(vlan_interface.upper())))
Vl99
```
