### ISSUE TITLE
interface range exponsion with ending "/1"

### ISSUE THREAD

**Issue by indy-independence** [networktocode/netutils#204]
### Environment
* Python version:  3.7.3
* netutils version:  1.4.0

### Expected Behavior
range expansion works for [49-50]/1 in same way as 1/[49-50]

### Observed Behavior
>>> interface_range_expansion("Ethernet1/[49-50]")
['Ethernet1/49', 'Ethernet1/50']
>>> interface_range_expansion("Ethernet[49-50]/1")
['Ethernet49', 'Ethernet50']

"/1" part is stripped away if it's on the end

### Steps to Reproduce
1. use interface_range_expansion()

**Comment by itdependsnetworks** [comment]
thanks for the report!

**Comment by abates** [comment]
I have seen this behavior. I will work on a fix. However, in the mean time there is a workaround that may work for you:

```python
>>> from netutils.interface import interface_range_expansion
>>> interface_range_expansion("Ethernet[49-50]/[1]")
['Ethernet49/1', 'Ethernet50/1']
````

Note the brackets around the `[1]`
