### ISSUE TITLE
Code Reference Documentation page for "Passwords" shows content for "ASN"

### ISSUE THREAD

**Issue by falz** [networktocode/netutils#205]
The readthedocs page for Passwords does not display any information about Passwords, it instead has identical contnet as the ASNs page:

* https://netutils.readthedocs.io/en/latest/dev/code_reference/password/
* https://netutils.readthedocs.io/en/latest/dev/code_reference/asn/

**Comment by itdependsnetworks** [comment]
Thanks for this!

Updated coming in #206

**Comment by itdependsnetworks** [comment]
https://netutils.readthedocs.io/en/latest/dev/code_reference/password/ renders correctly now
