### ISSUE TITLE
Add support for encrypting Cisco Type 9 password

### ISSUE THREAD

**Issue by alextremblay** [networktocode/netutils#215]
### Environment
* netutils version:  1.3.0

### Proposed Functionality
I would like to add an `encrypt_type9` function to `netutils.password`, with a similar signature to the existing `encrypt_type7` function.

### Use Case
This would allow users to generate valid cisco type 9 password hashes to be embedded in their configs or compared against existing hashes in existing configs.

**Comment by itdependsnetworks** [comment]
Going to consolidate and manage here: https://github.com/networktocode/netutils/issues/215
