### ISSUE TITLE
PyPI metadata

### ISSUE THREAD

**Issue by itdependsnetworks** [networktocode/netutils#22]
### Environment
* Python version:  3.7
* netutils version:  0.2.1

### Expected Behavior

Metadata populating PyPI.

### Observed Behavior

![image](https://user-images.githubusercontent.com/9260483/121621141-9368d600-ca39-11eb-8889-7da4dd71e709.png)

### Steps to Reproduce
1. Go to https://pypi.org/project/netutils/
2. View lack of info

**Comment by qduk** [comment]
#39 will copy over the README to the pypi page once that PR is merged to develop and a new release is cut.
