### ISSUE TITLE
Interface abbreviation for TwoGigabitEthernet

### ISSUE THREAD

**Issue by michaelklose** [networktocode/netutils#221]
### Environment
* Python version:  3.9.7
* netutils version:  1.4.1

### Expected Behavior
Abbreviation for TwoGigabitEthernet should be Tw e.g. Tw1/0/1

See Example output of a Cisco C9300-48UXM running 17.6.4
```
switch#show int status
Port         Name               Status       Vlan       Duplex  Speed Type
Tw1/0/1      test               notconnect   1          auto   auto 100/1000/2.5GBaseTX
```

### Observed Behavior
Currently the abbreviation is Two

### Steps to Reproduce
```
>>> from netutils.interface import abbreviated_interface_name
>>> abbreviated_interface_name("TwoGigabitEthernet1/0/1")
'Two1/0/1'
>>>
```

**Comment by michaelklose** [comment]
If issue is accepted you can assign it to me and I will open a PR.

**Comment by itdependsnetworks** [comment]
Please do : )
