### ISSUE TITLE
Add Interface type for Cisco App-hosting port

### ISSUE THREAD

**Issue by michaelklose** [networktocode/netutils#222]
### Environment
* netutils version:  1.4.1

### Proposed Functionality
Add Cisco App-hosting port to BASE_INTERFACES and REVERSE_MAPPING dict in netutils/constants.py

Example output from Cisco 9300-48UXM
```
switch#show int status | inc Ap
Ap1/0/1                         connected    1          a-full a-1000 App-hosting port

switch#show int ap1/0/1
AppGigabitEthernet1/0/1 is up, line protocol is up (connected)
  Hardware is App-hosting Gigabit Ethernet, address is abcd.1234.5678 (bia abcd.1234.5678)
```

I suggest adding the following options

```
BASE_INTERFACES = {
    "Ap": "AppGigabitEthernet",
    "ap": "AppGigabitEthernet",

REVERSE_MAPPING = {
    "AppGigabitEthernet": "Ap",
}
```

### Use Case
Support new interface type on Cisco Catalyst 9000 platform

**Comment by michaelklose** [comment]
If issue is accepted you can assign it to me and I will open a PR.

**Comment by itdependsnetworks** [comment]
Please do : )
