### ISSUE TITLE
IOS-XR Parser Support

### ISSUE THREAD

**Issue by jeffkala** [networktocode/netutils#26]
Environment
Python version: 3.8
Nautobot version: 1.0.1
nautobot-golden-config version: develop
Proposed Functionality
Add a parser for IOSXR

Use Case
Already seen it be requested a few times in public chat

**Comment by jlixfeld** [comment]
I'm one of the folks who mentioned this early on in 2021 and am still very much interested in seeing this come to fruition.

**Comment by jdrew82** [comment]
This is also noted in #86.

**Comment by jeffkala** [comment]
@jlixfeld If you want to help move ios-xr forward anyway you can provide a sanitized config? In a gist or whatnot would be fine.

**Comment by jlixfeld** [comment]
I emailed one to tim.schreyack.  I can email to you directly if you'd like, otherwise.
