### ISSUE TITLE
"Abbreviated Interface Name" method does not work for "FourHundredGigabitEthernet" interfaces (iosxr)

### ISSUE THREAD

**Issue by Kani999** [networktocode/netutils#282]
### Environment
* Python version:  3.10.6
* netutils version:  1.41

### Expected Behavior
Return abbreviated interface name `FH0/0/1/4`

### Observed Behavior
Returned canonical name `FourHundredGigabitEthernet0/0/1/4`

### Steps to Reproduce
```python
from netutils.interface import abbreviated_interface_name

print(abbreviated_interface_name("FourHundredGigabitEthernet0/0/1/4"))
```

**Comment by qduk** [comment]
@Kani999 Thanks for that. #285 has been opened to resolve the issue.
