### ISSUE TITLE
Golden Config Compliance Rule Backend Modification

### ISSUE THREAD

**Issue by KochTushas1** [networktocode/netutils#301]
Hey Team,

So, this is for the compliance rule in golden config, as you know today, we are just using "startswith" logic in our compliance rule creation. It is not fulfilling 100% requirement today. But if we can add regex into it then it can create a serious impact and improve the compliance output also.

Here is the example of snmp config:

snmp-server
access-list
logging trap
logging host

So, the logging host here when get matched with intended and actual config, it will give non-compliant status for more than 1 ip addresses. so today there is no way to capture something like this:

logging host 1.1.1.1
logging host 2.2.2.2
logging host 3.3.3.3

But if we can use regex in this case then the scenario will be different like this:
logging host <regex for ip>

**Comment by itdependsnetworks** [comment]
Duplicate #60
