### ISSUE TITLE
Interface mapping for "Fi": "FiftyGigabitInternet" mistranslates Cisco's "FiveGigabitInterface"

### ISSUE THREAD

**Issue by rlad78** [networktocode/netutils#390]
### Environment
* Python version:  3.10.4
* netutils version:  1.0.0

### Expected Behavior
`BASE_INTERFACES` map in `netutils/constants.py` would properly recognize the Cisco Catalyst "Fi" interface abbreviation as "FiveGigabitEthernet"

### Resulting Behavior
`BASE_INTERFACES` has "Fi" mapped to "FiftyGigabitEthernet"

https://github.com/networktocode/netutils/blob/4f2fdf3f39995604e2db941204b3172490b028ac/netutils/constants.py#L47-L48

### Steps to Reproduce
I'm not actually familiar with netutils, but I use [Nautobot](https://github.com/nautobot/nautobot/tree/develop), which has [Napalm](https://github.com/napalm-automation/napalm) as a dependency (which, in turn, uses netutils as one of its dependencies). When trying to do work in Napalm on one of our Cisco Catalyst 9300 switches, we noticed that we were getting incorrect interface name expansions.

For example, an interface abbreviated as `Fi1/0/1` should result in `FiveGigabitEthernet1/0/1`, as that's what it is labeled as on the Cisco device. However, we see it appear as `FiftyGigabitEthernet1/0/1`. 

I went through the history of the constants file and couldn't determine this, but is there a specific manufacturer/platform that uses 'Fi' for FiftyGigabitEthernet? And if not, could it potentially be replaced with 'FiveGigabitEthernet'?

**Comment by scetron** [comment]
This might be tough as it appears there is some overlap between Five and Fifty GigabitEthernet interfaces...

Guide with reference to FiftyGigabitEthernet 
https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9500/software/release/17-10/configuration_guide/qos/b_1710_qos_9500_cg/configuring_qos_c9500x.html

**Comment by jeffkala** [comment]
To make sure in the catalyst device `Fi` is a valid abbreviation and automatically interprets that as FiveGi since FigtyGig is probably not a valid interface type/size on that hardware/platform?

**Comment by rlad78** [comment]
> To make sure in the catalyst device `Fi` is a valid abbreviation and automatically interprets that as FiveGi since FigtyGig is probably not a valid interface type/size on that hardware/platform?

Apologies, I didn't see this reply until now. Yes, but it's a bit more complicated unfortunately. The platform supports both FiveGig and FiftyGig interfaces, but there don't seem to be any models that have both types of interfaces on the same hardware. Please read below.


> This might be tough as it appears there is some overlap between Five and Fifty GigabitEthernet interfaces...
> 
> Guide with reference to FiftyGigabitEthernet https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9500/software/release/17-10/configuration_guide/qos/b_1710_qos_9500_cg/configuring_qos_c9500x.html

@scetron according to an example in [this section](https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9500/software/release/17-10/configuration_guide/qos/b_1710_qos_9500_cg/configuring_qos_c9500x.html#examples_tcp_protocol_classification) on that page, Cisco uses `fif` as the FiftyGig abbreviation in IOS-XE:

```
Device# show run int fif 1/0/1

Current configuration : 93 bytes
!
interface FiftyGigE1/0/1
 no ip address
 no keepalive
 service-policy input tcp
end
```

I don't have a Catalyst 9000 series device with a FiftyGig interface unfortunately, so I can't confirm whether IOS-XE will accept `fi` as an abbreviation for FiftyGig or not. I originally thought they'd have to have some kind of separation between FiveGig and FiftyGig abbreviations for cases where a model has both FiveGig and FiftyGig interfaces, but I can't find any models on [the Cisco C9500 datasheet](https://www.cisco.com/c/en/us/products/collateral/switches/catalyst-9500-series-switches/nb-06-cat9500-ser-data-sheet-cte-en.html) that has both. The C9600 series has different line cards with 5G and 50G interfaces, but it doesn't seem like you can combine them on a single chassis...

![image](https://github.com/networktocode/netutils/assets/5733291/db7a3ef8-562e-4f1e-9346-b8b1871bb23e)

If anyone out there has a Cisco C9500 switch with a FiftyGigE interface, and can test to see if `fi` works as an abbreviation for FiftyGigE, that would confirm that there isn't a way to differentiate the interface from a FiveGigE interface by abbreviation on IOS-XE. If only `fif` works as the abbreviation for FiftyGigE, that means that `fi` could be specifically reserved for FiveGigE interfaces.

**Comment by itdependsnetworks** [comment]
Unfortunately there isn't anything we can do, but if you have to override you can do 1 of 2 things

1. Use the `addl_name_map` when calling `canonical_interface_name`
2. Overwrite the memory, such as 


```python
form netutils.constants import BASE_INTERFACES

BASE_INTERFACES[ "Fi"] = "FiveGigabitEthernet"
```

There really is no way around this, and I think fiftygigabitethernet is the more popular of the two, which is somewhat irrelevant in not wanting to change something that would break backwards compat.

See https://github.com/networktocode/netutils/issues/158#issuecomment-1287046776 as well.
