### ISSUE TITLE
When the compliance rules with "banner" congif to match, it will failed to exec compliance

### ISSUE THREAD

**Issue by alicechiou** [networktocode/netutils#401]
### Environment
* Python version:  3.8.13
* netutils version:  1.6.0

when I add a compliance rule which config to match value is "banner exec", t should compare the backup configuration and the intended configuration to see if the sentence "banner exec" exists

It shows the error "RENDER COMPLIANCE TASK GROUP failed: Unable to parse banner end."

### Steps to Reproduce
1. add a device which backup config has "banner exec" value.
2. add a device which intended config has "banner exec" value.
3. add a compliance feature called "test", and setup a compliance rule which  config to match value is "banner exec",
4. execute config compliance

![image](https://github.com/networktocode/netutils/assets/39262687/a1939144-8b65-4f49-a0b9-a99adf05a5d6)

![image](https://github.com/networktocode/netutils/assets/39262687/bf96a0d2-f7ae-47b6-8ab8-1542eea3b896)

![image](https://github.com/networktocode/netutils/assets/39262687/10d7b041-ade9-4b5a-9c2e-6eeabc001487)

**Comment by itdependsnetworks** [comment]
banners are problematic, but we would need to see the actual banner. Can you confirm this is not an issue with the intended state vs the actual state?

**Comment by jeffkala** [comment]
Also what platform is TestSwitch_as_3 ? IOS, NXOS, Arista etc.

**Comment by alicechiou** [comment]
Hi, @jeffkala and @itdependsnetworks 
Please refer to https://github.com/nautobot/nautobot-plugin-golden-config/issues/662
The platform of TestSwitch_as_3 is ios.
And I paste the value of our actual config.
In my backup config:
The value is
![image](https://github.com/networktocode/netutils/assets/39262687/60856200-773c-4f3c-8902-225cad40a658)

And I can set the compliance rule with value: banner exec ^C
and it can be compared and showed in the config compliance page. 
![image](https://github.com/networktocode/netutils/assets/39262687/0836fcf1-b173-4374-a910-717bafaa587a)

But if I changed the value to banner motd ^C, it would be failed.

**Comment by jeffkala** [comment]
fixed in #509
