### ISSUE TITLE
`lib_mapper`: `fortinet` vs `fortinet_fortios` normalized name?

### ISSUE THREAD

**Issue by u1735067** [networktocode/netutils#402]
Hi, 

is it normal that 2 normalized names exists for Fortinet FortiOS?

### Environment
* netutils version: 1.6.0

### Expected Behavior
An unique normalized name is defined for Fortinet FortiOS

### Observed Behavior
2 names exists: `fortinet` (`NAPALM_LIB_MAPPER`) and `fortinet_fortios` (`NETUTILSPARSER_LIB_MAPPER` ; which seems to be the right name, as `fortinet` is a vendor?)

### Steps to Reproduce
1. Browse https://netutils.readthedocs.io/en/latest/user/lib_use_cases_lib_mapper/ / https://github.com/networktocode/netutils/blob/v1.6.0/netutils/lib_mapper.py
2. Search "forti"

**Comment by jeffkala** [comment]
Thanks for the report @u1735067 , we're reviewing internally. It definitely does appear we have some logic that needs to be fixed, but trying to determine the right one.
Typically netutils parser key matches netmikos but for this case netmikos is actually just `fortinet` so we may just need to update that single mapping.

**Comment by jeffkala** [comment]
Bit complicated as well because both of these are viable options in the napalm space.
`fortios` = https://github.com/glennake/napalm-fortios
`fortinet` = https://github.com/glennake/napalm-fortinet

So that may be where some of the confusion is.

**Comment by itdependsnetworks** [comment]
yes, this should be fixed in #443, I am sure it will make someone unhappy, but really have no choice in order to make consistent.
