### ISSUE TITLE
Library mapping for netmiko `cisco_xe` not fully implemented

### ISSUE THREAD

**Issue by whitej6** [networktocode/netutils#414]
### Environment
* Python version:  3.11
* netutils version:  latest

### Expected Behavior
Provide ability for forward mapping of `cisco_xe` to other library types, existing mappings should remain the same.

### Observed Behavior
`cisco_xe` for napalm & ansible mappings

### Steps to Reproduce
1.
2.
3.

**Comment by qduk** [comment]
Ansible: `cisco_xe` -> `cisco.ios.ios`
Hierconfig: `cisco_xe` -> `ios`
Napalm Mapping: `cisco_xe` -> `cisco_ios`
Netmiko: No change
NTC Templates: No change
PyAts: `cisco_xe` -> `iosxe`
PyNTC: `cisco_xe` -> `cisco_ios_ssh`
Scrapli: No change

This is what we came up with @whitej6. Thoughts?

**Comment by whitej6** [comment]
That's more exhaustive than I initially asked for and I think it's great!
