### ISSUE TITLE
Library Mapper - [Reverse] Napalm Mapper - inverted huawei values 

### ISSUE THREAD

**Issue by AlanKane640** [networktocode/netutils#415]
Hi,

Actually, in the Napalm Mapper,we have : 
huawei (Napalm) → huawei_vrp (Normalized)

No Napalm "huawei" driver exists but "ce" and "huawei_vrp" drivers exist, so, does the right mapper should not be : 
- huawei_vrp (Napalm) → huawei (Normalized), for Napalm Mapper
- huawei (Normalized) → huawei_vrp (Napalm), for Reverse Napalm Mapper
?

**Comment by qduk** [comment]
Thanks @AlanKane640. This is indeed an error on our part. We'll get this fixed.
