### ISSUE TITLE
Normalize cisco_iosxr -> cisco_xr

### ISSUE THREAD

**Issue by CHEDARBOB** [networktocode/netutils#422]
### Environment
* Python version:  3.11
* netutils version: latest

### Expected Behavior
Map cisco_iosxr to (normalized) cisco_xr for NETUTILSPARSER

### Observed Behavior
No/Incorrect mapping from cisco_iosxr to (normalized) cisco_xr

Using Nautobot Golden Config Compliance got E3003
"E3003: There is currently no CLI-config parser support for platform network_driver cisco_xr, preemptively failed."
Note: If this issue should be handled/created under nautobot/nautobot, I will create one there and this issue can be closed.

### Steps to Reproduce
1. 
2.
3.

**Comment by qduk** [comment]
Thanks @CHEDARBOB. It does look like this should be `cisco_xr`. I'll verify internally and get a PR opened up.
