### ISSUE TITLE
Protocol Name to Number Map Missing Essentials

### ISSUE THREAD

**Issue by jdrew82** [networktocode/netutils#492]
### Environment
* Python version:  3.9
* netutils version:  1.7.0

### Expected Behavior
PROTO_NAME_TO_NUM list to include mappings for IPv4/v6, and ICMPv6.

### Observed Behavior
PROTO_NAME_TO_NUM list is missing IPv4, IPv6, and ICMPv6.

### Steps to Reproduce
1. Look at PROTO_NAME_TO_NUM list.
2.
3.

**Comment by jeffkala** [comment]
fixed in #494
