### ISSUE TITLE
parsing of empty banner fails

### ISSUE THREAD

**Issue by milan2655** [networktocode/netutils#502]
### Environment
* Python version:  3.11.8
* netutils version:  1.7.0 

Parsing of empty **cisco_ios** banner fails. The banner has just one line in the configuration and  because of that method **_build_banner** cannot find its end based on '^C' character. 
```
self.banner_end
'^C'
```

This is the exception:
**ValueError: Unable to parse banner end.**

### Steps to Reproduce
1. create empty banner in cisco device:
```
banner motd aa
```
2. confirm banner (show run | beg banner motd):
```
banner motd ^C^C
!
line con 0
....
```

Exception: 

  File ".venv/lib/python3.11/site-packages/netutils/config/parser.py", line 548, in _build_banner
    return super(CiscoConfigParser, self)._build_banner(config_line)
  File ".venv/lib/python3.11/site-packages/netutils/config/parser.py", line 231, in _build_banner
    raise ValueError("Unable to parse banner end.")
ValueError: Unable to parse banner end.

**Comment by itdependsnetworks** [comment]
I am not fully following, if I understand, the banner in the example should say `aa`.

**Comment by jeffkala** [comment]
a is the delimiter in this case, what I'm not following is why do you want a empty banner?  Just don't configure the banner at that point.

**Comment by milan2655** [comment]
hallo jeff!

_compliance task_ in the _nautobot_golden_config_ plugin is failing, because it cannot pars the config. 

`config_parsed = os_parser(device_cfg)` -> this is the problematic line of code

if by some strange reason a device's config contains an empty banner the hole compliant_job fails.

my example with `aa` is just how to recreate the empty banner on the _cisco_ios_ device. my purpose is not tho create empty banner, but due to the mistake during the configuration of a device, some devices in the network have empty banner.

_golden_config_ plugin cannot detect this devices, because the job fails. our only workaround is to finde this devices and to remove wrong banner manually.

did you get the problem now?

**Comment by jeffkala** [comment]
Understood, will look at creating a failing tests case to work on a fix.

**Comment by jeffkala** [comment]
Failed/duplicated test has been created. So now when someone takes a try at fixing it they have a test to validate against.
