### ISSUE TITLE
Convert banner delimiter

### ISSUE THREAD

**Issue by qduk** [networktocode/netutils#67]
### Environment
* netutils version:  0.2.3

### Proposed Functionality
When pulling device configuration via different methods (FTP, SSH, etc) the delimiter character differs. The goal would be to find the banner delimiter in the configuration and convert it between ^, ^C, ETX. 

### Use Case

- 'ETX' is when FTP, TFTP, etc
- '^' is the config standard for applying configuration. 
- '^C' is the config standard that shows in the config. 

Whenever comparing or reasonably wanting to leverage a single config to both compare and push configurations, this would allow easy replacement of delimiters.

### API
def etx_to_caret()
def etx_to_caretc()
def caret_to_etx()

OR

def delimiter_change(s_type=caret, d_type=etx)

**Comment by jeffkala** [comment]
Need to validate, but believe this was addressed by #69

**Comment by jeffkala** [comment]
fixed #69 by @pke11y
