### ISSUE TITLE
Add function to generate PTR record from IP address

### ISSUE THREAD

**Issue by dgarros** [networktocode/netutils#87]
### Environment
* netutils version:  1.0.0

### Proposed Functionality
Add a function that will generate a PTR record from an IP address for v4 and v6

```
>>> ip4_to_ptr("1.0.2.254")
"254.2.0.1.in-addr.arpa."

>>> ip6_to_ptr("2001:db8::1")
"1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa."
```

**Comment by qduk** [comment]
This capability exists in the library currently. You can use `netutils.ip.ipaddress_address` method to get the same thing.
