### ISSUE TITLE
Junos List Jinja Filter

### ISSUE THREAD

**Issue by minitriga** [networktocode/netutils#92]
### Environment
* netutils version:  * any future version

### Proposed Functionality
Junos requires lists to be formatted inline and within square brackets that are spaced. For example `authentication-order [ password radius ];` I propose a function to take a list and output a string that formats the list correctly. If there is only one item in the list the data is represented in the following format: `authentication-order password;`. 

### Use Case
Lets day we are doing `Network as Code` using Ansible and have defined the authentication order as the following:
```yaml
authentication_order:
  - password
  - radius
```

it would be nice to be able to easily convert the list above to valid junos syntax:
```jinja
authentication-order {{ authentication_order | junos_list }};
```

output but also handling the single item edge case:
```
authentication-order [ password radius ];
```

**Comment by itdependsnetworks** [comment]
Is `authentication-order [ password radius "your spaced value"];` a valid option?

**Comment by minitriga** [comment]
I don't think so. But will confirm this tomorrow when I login.

**Comment by jeffkala** [comment]
Pretty sure `"` are not allowed inside the square brackets.

**Comment by minitriga** [comment]
After testing it... It looks like you can have `"` within the list. 

```
root@SRX# set system authentication-order ["password" "radius"]

[edit]
root@SRX# show | compare
[edit system]
+  authentication-order [ password radius ];

[edit]

```

**Comment by jeffkala** [comment]
@minitriga I think what @itdependsnetworks was asking is if the below would work.  You mind trying this.
`set system authentication-order ["password radius"]`

**Comment by jeffkala** [comment]
Also not really sure a new jinja2 filter would be needed.  A simple join should do the trick.

```
---
- name: TEST
  gather_facts: false
  hosts: localhost
  vars:
    authentication_order:
      - password
      - radius
  tasks:
    - name: "DEBUG"
      debug:
        msg: "authentication-order [ {{ authentication_order | join(' ') }} ]"
```

resulted in
```
TASK [DEBUG] **********************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "authentication-order [ password radius ]"
}
```

**Comment by jeffkala** [comment]
@minitriga any update? Going to close during our next review (2 weeks from now) otherwise.
