### ISSUE TITLE
Napalm Supported Getter Matrix (as code)

### ISSUE THREAD

**Issue by jeffkala** [networktocode/netutils#95]
### Environment
* netutils version:  future

### Proposed Functionality
A mapper function to be able to find supported napalm getters in a programatic way.  Would essentially map https://napalm.readthedocs.io/en/latest/support/#getters-support-matrix into a dictionary of sorts.

### Use Case
UI interface of an application allows you to utilize Napalm as a connection type, it then has a drop down of supported getters based on the platform selected.

**Comment by jeffkala** [comment]
Potentially update for pyats and ntc-templates parsers support as well.

**Comment by jeffkala** [comment]
Method to pull whats already on "the" system and installed vs. what exist that library is capable of.

**Comment by Kircheneer** [comment]
If I understand this correctly, this does just that: https://github.com/napalm-automation/napalm/blob/0d3142bd3c5a248d2889cc1908af7e8d38767fca/docs/conf.py#L359
